server:
  port: 20111

spring:
  datasource:
    url: jdbc:mysql://rm-wz96b2k2ttoh6apb03o.mysql.rds.aliyuncs.com:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: shaoqi
    password: SHAOqi19990106
  main:
    allow-circular-references: true

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
